### ISSUE TITLE
allow custom value of parameter 'token_type'

### ISSUE THREAD

**Issue by kmilodenisglez** [guillp/requests_oauth2client#15]
- `requests_oauth2client` version: 1.1.0
- Python version: 3.9
- Operating System: Windows 10

### Description

The authorization server I'm trying to communicate with returns the bearer token with this structure:
```json
{'token_type': 'BearerToken'}
```
and the **requests_oauth2client** library expects the following structure:
```json
{'token_type': 'Bearer'}
```

_It would be a good option for this library to accept modifying the value of the '**token_type**' parameter._

**Comment by guillp** [comment]
First: this should really be fixed on server side since it is a clear violation of the OAuth 2.0 specification. 
That being said, I pushed a small code change so this can be supported, see the commit above and its associated test case, and let me know if that works for you. You can install the test version from here: https://test.pypi.org/project/requests-oauth2client/#files

**Comment by kmilodenisglez** [comment]
Hi @guillp

Great, I tried it and it worked fine.

_Thank!!_
