### ISSUE TITLE
Support `alg="RS256"` for signed BackChannel Authentication requests

### ISSUE THREAD

**Issue by AlexanderFL** [guillp/requests_oauth2client#44]
- `requests_oauth2client` version: 1.3
- Python version: 3.10.8
- Operating System: Windows 10/Linux

### Description

I'm trying to call `backchannel_authentication_request` from an `OAuth2Client` with the algorithm `RS256` set as a parameter. This is the exception I'm receiving:

> UnsupportedAlg: Alg RS256 is not supported. Supported algs: ['HS256', 'HS384', 'HS512'].

My OpenID Provider mandates that the JWT is signed with my private key and he has the corresponding public key.

### What I Did

```python3
client = OAuth2Client(
    token_endpoint=token_url,
    backchannel_authentication_endpoint=auth_url,
    auth=(client_id, client_secret),
)

ba_response = client.backchannel_authentication_request(
    scope="openid profile",
    login_hint=login_hint,
    binding_message=binding_message_payload,
    binding_content=binding_content,
    user_code=verification_code,
    requested_expiry=90,
    alg="RS256",
    private_jwk=private_key.encode("utf-8"),
)
```

Would you be open to adding support for this scenario? Thanks

**Comment by guillp** [comment]
So you are trying to send an asymmetrically signed request to the BackChannel Authentication Endpoint ?

Everything should be already in place in `requests_oauth2client`, but I think the issue is there:

```python
 ba_response = client.backchannel_authentication_request(
    scope="openid profile",
    login_hint=login_hint,
    binding_message=binding_message_payload,
    binding_content=binding_content,
    user_code=verification_code,
    requested_expiry=90,
    alg="RS256",
    private_jwk=private_key.encode("utf-8"),
)
```

I don't know (and I don't want to know ;) ) what value is in your `private_key` , but since you are encoding it to "utf-8" I believe it is a string. So it is considered as a symmetric key and is used as such for signing. And you can only use symmetric signature algorithm (HS{256,384,512}) with a symmetric key.
If you want to use an asymmetric signature algorithm (which is a good idea), you need to give a private asymmetric key of the appropriate type$. Either an instance of a `cryptography` key (`cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKey` in your case) or a JWK, as an instance of `jwskate.Jwk` with `kty="RSA"`. You can generate one with `from jwskate import Jwk; private_jwk = Jwk.generate(alg="RS256")`.

Last note: I did implement Signed BackChannel Authentication based on standard specifications, but I did not test it with a "real" AS. If you encounter any issue, feel free to open another bug report.

**Comment by AlexanderFL** [comment]
This is the working JWT header

```json
{
  "alg": "RS256",
  "typ": "JWT"
}
```
and the payload (I'll remove some sensitive information)
```json
{
  "login_hint": "<phone number>",
  "scope": "openid profile signature",
  "acr_values": "sim-auth",
  "iss": "<my client id>",
  "aud": "<issuer URL>/sso/oauth2/realms/root/realms/<issuer>",
  "exp": 1706541248.245817,
  "binding_message": "Login [JTest], code: 1534",
  "binding_content": "lpTYNBkjloHvBpuUE4HHDE0JQOdO2RuSDZhEeKFY58aQy2nROLXkb+rD07P0HrhhrKMq02bj6f0YDB1GVA/uLQ=="
}
```

Unfortunately, I don't have access to the logs from the OpenId provider which is a semi-governmental company that manages identity for individuals in my country.

There is no `kid` needed to my knowledge, since they have received a copy of my public key on their side which is bound to my client_id

---

Just for completeness, this is how I'm constructing the JWT using the `pyjwt` library

```python
jwt_header = {"alg": "RS256", "typ": "JWT"}

jwt_payload = {
    "login_hint": login_hint,
    "scope": scope_payload,
    "acr_values": acr_value,
    "iss": client_id,
    "aud": audience,
    "exp": expiry,
    "binding_message": binding_message,
    "binding_content": binding_content,
}

return jwt.encode(
    jwt_payload,
    key=private_key,
    algorithm="RS256",
    headers=jwt_header
)
```

**Comment by AlexanderFL** [comment]
I think I figured out what's happening, and it has to do with some `kid` header being set here

https://github.com/guillp/requests_oauth2client/blob/0542bbb4e4c68f06b72d61c0c83b0bc66ef3e184/requests_oauth2client/client.py#L1112

Since my provider is complaining about an invalid signature, I assume that whatever implementation they're using tries to look up the KID, fails, and automatically rejects it. Because if I send the exact same payload without this `kid` header, everything works perfectly.

**Comment by guillp** [comment]
Ah, then the issue is indeed related to the key ID.
I guess you have jwskate==0.11 installed. A kid is always included in signed JWT with this version (which looks like was not a good idea after all...)

The rationale is: when you generate a private key, you should always give it a Key ID (kid). And when you sign a JWT, you should always include the kid as a header. This way, if you renew that key, you can give the new key (and new kid) to the other party, and he can rely on the Key ID to automatically pick the appropriate key (instead of having to try with all the keys, or having to come up with some other heuristic). The issue with the `kid` is that it a JWK specific field and it is not part of PEM. You can use the key thumbprint which is basically a hash of the public part of the key, so its value it "kept" even if it is not part of the PEM.
Obviously that only works when the verifying party gets its public keys in JWK format.

With `jwskate`, you can simply use `jwk = Jwk.from_pem("<yourprivatepem>").with_kid_thumbprint()` to get the JWK with the kid as thumbprint. Use `jwk.public_jwk()` to get the public JWK with the kid (that part you give to the AS).
