### ISSUE TITLE
DPoP: How to retry with nonce from server?

### ISSUE THREAD

**Issue by elonen** [guillp/requests_oauth2client#97]
- `requests_oauth2client` version: main (447c870)
- Python version: 3.12
- Operating System: Windows

### Description

When calling `client.client_credentials(...)` with a DPoP key, I'm receiving `UseDPoPNonce` from the server. 

I can get the new nonce from the exception object as `e.response.headers['dpop-nonce']`, but then can't figure out how to actually pass it to the subsequent calls. For example: 

```python
client = OAuth2Client(
    token_endpoint=token_endpoint,
    client_id=client_id,
    client_secret=client_secret,
    dpop_bound_access_tokens=True,
    authorization_endpoint=f'https://{okta_domain}/oauth2/v1/device/authorize'
)

# Fetch the DPoP-bound access token
token = None
try:
    token = client.client_credentials(dpop_key=dpop_key, dpop=True, scope='okta.users.read')
except UseDPoPNonce as e:
    nonce = e.response.headers['dpop-nonce']
    token = client.client_credentials(dpop_key=dpop_key, dpop=True, scope='okta.users.read', # NOW WHAT..?
```

**Comment by guillp** [comment]
Thanks for the report.
First disclaimer, support for DPoP is currently not complete and fully tested, and your bug report is a good proof of that. You should not have to handle the `use_dpop_key` signal yourself, it should be handled transparently by `OAuth2Client`. There might be an issue when forcing a pre-generated dpop_key. I'll need to test it further.
Can you try to set `dpop_key.as_nonce` to the retrieved nonce before you call `client.client_credentials` again ?
So basically add this line between the last 2 lines of your sample: `dpop_key.as_nonce = nonce`. 

That aside, do you really need to pass your own pre-generated `dpop_key`? Since you enabled dpop by default with `dpop_bound_access_tokens=True` when initializing your client, if you simply do `client.client_credentials(scope="okta.users.read")`, then a dpop key will be automatically generated and used, and the eventual AS provided nonce will be obeyed transparently. That is a code path I successfully tested already.

**Comment by elonen** [comment]
Thank you for the swift answer!
Neither of the options worked:

- Setting `dpop_key.as_nonce` caused `attr.exceptions.FrozenInstanceError` 
- Removing the explicit key still raised `UseDPoPNonce`, and retrying it in the except block (without any changes), just raised it again

**Comment by guillp** [comment]
Try this branch: https://github.com/guillp/requests_oauth2client/tree/feature/dpop_nonce (PR is in progress: #92)
The main branch does not handle DPoP nonces yet

**Comment by elonen** [comment]
👍 The feature branch seems to work both with an without an explicit key. Thanks again.

("Seems" because now I'm getting "_One or more scopes are not configured for the authorization server resource_", which sounds like the token I received is too restricted - oh well.)
